# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtZjtn8Mf8Erd7rV_EI-Try5tgAzzF6-
"""

#number guessing game
#step 1:import module
import random
#step 2:ramdom values
secret_number=random.randint(1,100)
attempts=0 #guess counter
#step 3:
print("welcome to the guessing number game and /n i have chosen number between 1 and 100")
#step 4:gaming loop
while True:
    guess=int(input("enter your guess:"))
    attempts+=1 #increase 1 digit every time whenever program execute
    if guess< secret_number:
        print("its too low! try again")
    elif guess> secret_number:
        print("its too high !")
    else:
        print("congratulations!you guessed it in{attempts}attempts")
        break#loop end